apiVersion: v1
kind: Pod
metadata:
  labels:
    component: rabbitmq
  name: wa8g
spec:
  automountServiceAccountToken: false
  dnsPolicy: ClusterFirstWithHostNet
  hostname: wa8g
  nodeName: demonode02
  volumes:
    - name: cam
      hostPath:
        path: /dev/video0
  containers:
  - image: rabbitmq
    name: rabbitmq
    ports:
    - containerPort: 5672
    imagePullPolicy: IfNotPresent
  - name: producer
    image: erenart/wa8g-edge:ARM32-Workload
    command: ["/bin/sh"]
    args: ["-c","python3 WaggleProducer/image_producer.py /dev/waggle_cam_bottom wa8g"]
    imagePullPolicy: IfNotPresent
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /dev/waggle_cam_bottom
      name: cam
  - name: consumer
    image: erenart/wa8g-edge:ARM32-Workload
    command: ["/bin/sh"]
    args: ["-c","cd WaggleProducer/ && python3 plugin_bin/plugin_node"]
    imagePullPolicy: IfNotPresent
  restartPolicy: OnFailure
